apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 164743751473.dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newName: 164743751473.dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newTag: c1b1ef85
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
